#!/bin/bash

for topDir in *
do

	if [ -d "$topDir" ]
		then
		echo Directory: "$topDir"
		cd "$topDir"
		cd "DegreeData"

		# set temp test window data file, until model does it
		rm windowData


		# Enter each degreeDist Data folder
		for degreeDist in *degreeDistData
		do
			if [ -d $degreeDist ]
				then
				cd "$degreeDist" 	# enter data folder
				mkdir plots			# make plots folder

				degreeMax=`sed '1q;d' windowInfo.txt`
				percentMax=`sed '2q;d' windowInfo.txt`

				echo "$degreeMax"
				echo "$percentMax"
				count=1
				
				orderedData=`ls *.dat | sort -n -t p -k 2`
				echo $orderedData
				for data in $orderedData
				do
					echo start GNUPlot
					echo "$degreeDist" "$data"
					echo "$count"

					## GNU Plot Stuff
					gnuplot <<- EOF
						set title "Degree Distribution Plot"
						set xlabel "Degree"
						set ylabel "Percentage"
						set term gif
						set xrange [0:${degreeMax}]
						set yrange [0:${percentMax}]
						set output "plots/DegreeDistPlot_step${count}.gif"
						plot "${data}" with lines
					EOF

					(( count++ ))

					echo Done GNUPLOT



				done
				cd ..
			fi
		done

		# go back to top folder
		cd ../..
	else
		echo non-Dir: "$topDir"
	fi
done