#!/bin/bash

plotList=`ls *.dat | sort -n -t _ -k 2`

mkdir plots

count=1





for data in $plotList
        do
          echo start GNUPlot
          echo "$count"

          ## GNU Plot Stuff
          gnuplot <<HERE
            set title "Betweenness Plot"
            set xlabel "Sorted Nodes"
            set ylabel "Betweenness Score"
            set term gif
            set output "plots/BetweennessPlot_${count}.gif"
            plot "${data}" with lines
HERE

          (( count++ ))

          echo Done GNUPLOT
        done
