#!/bin/bash

for m in ModelRun_*
do

  cd $m
  for d in ModelRun_*
  do
    cd $d
    cp ../../Regression_Plot.r .
      for f in run*
      do
        Rscript Regression_Plot.r $f 9 10
      done
    mkdir Reg
    mv *Regression* Reg/
    cd ..
  done
  cd ..
done
